version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbcontainer
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - network-namin

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mariadb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 500
      SERVER_PORT: 3000
      VIRTUAL_HOST: "api.pokeafk.online"
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: "api.pokeafk.online"
      LETSENCRYPT_EMAIL: "namigame@gmail.com"
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - network-namin

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENABLE_IPV6: "true"
    volumes:
      - ~/nginx/vhost.d:/etc/nginx/vhost.d
      - ~/nginx-certs:/etc/nginx/certs:ro
      - ~/nginx-conf:/etc/nginx/conf.d
      - ~/nginx-logs:/var/log/nginx
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - network-namin

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    privileged: true
    volumes:
      - ~/nginx/vhost.d:/etc/nginx/vhost.d
      - ~/nginx-certs:/etc/nginx/certs:rw
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - network-namin

networks:
  network-namin:
    external: true
