version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbcontainer
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mariadb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 500
      SERVER_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - internalnet

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - internalnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
    networks:
      - internalnet
        
networks:
  internalnet:
    driver: bridge
