FROM jwilder/nginx-proxy

# Copy nginx.conf to the container's Nginx configuration directory
COPY nginx.conf /etc/nginx/nginx.conf

# Copy vhost.d configurations
COPY nginx.vhost.d /etc/nginx/vhost.d
