# Dockerfile for nginx-proxy
FROM jwilder/nginx-proxy

# Copy custom configuration files
COPY nginx.vhost.d /etc/nginx/vhost.d
COPY nginx.certs /etc/nginx/certs
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80
EXPOSE 443

# Set environment variables
ENV ENABLE_IPV6=true

# Entrypoint
CMD ["nginx", "-g", "daemon off;"]
