version: '3'

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp:v1
    environment:
      - VIRTUAL_HOST=api.pokeafk.online
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.pokeafk.online
      - LETSENCRYPT_EMAIL=devnami@gmail.com
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - internalnet

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile.nginx-proxy
    image: nginx-proxy:v1
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.vhost.d:/etc/nginx/vhost.d
      - ./nginx.certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    networks:
      - internalnet

  letsencrypt:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile.letsencrypt
    image: letsencrypt-companion:v1
    container_name: letsencrypt
    volumes:
      - ./nginx.vhost.d:/etc/nginx/vhost.d
      - ./nginx.certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
