version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbcontainer
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306  
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mariadb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 500
      SERVER_PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - mariadb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
