version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbcontainer
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - bridge

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mariadb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 500
      SERVER_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
