version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbcontainer
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mariadb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 500
      SERVER_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - internalnet

  nginx:
    image: nginx:latest
    container_name: nginxcontainer
    restart: unless-stopped
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt  # Shared volume
    depends_on:
      - nodeapp
    networks:
      - internalnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt  
      - ./certbot/www:/var/www/certbot  
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    command:  --webroot --webroot-path=/var/www/certbot -d api.pokeafk.online --email quangtrung01654748714@gmail.com --agree-tos --no-eff-email
    depends_on:
      - nginx
    networks:
      - internalnet


volumes:
  certs:
networks:
  internalnet:
    driver: bridge
